# Generated by Django 4.2.3 on 2023-08-02 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MonopolyCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_monopoly', models.CharField(max_length=100)),
                ('description', models.TextField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_organization', models.CharField(max_length=100)),
                ('description', models.TextField(default=None)),
                ('district_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.district')),
                ('monopoly_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.monopolycompany')),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=7)),
                ('name_product', models.CharField(max_length=50)),
                ('price', models.FloatField()),
                ('description', models.TextField(default=None)),
                ('district_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.district')),
                ('organization_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.organization')),
            ],
        ),
    ]
